import type { Metadata } from "next";
import "./globals.css";
import { Inter, PT_Serif } from "next/font/google";
import { Nav } from "@/components/Nav/Nav";
import clsx from "clsx";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const pt = PT_Serif({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "The Preschool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx("bg-background", pt.className)}>
        <Nav className="" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
